import OpenAI from 'openai';

// ─── Types ────────────────────────────────────────────────────────────────────

export interface FailureContext {
  scenarioName: string;
  featureFile: string;
  tags: string[];
  errorMessage: string;
  stackTrace: string;
}

export interface AnalysisResult {
  isBug: boolean;
  confidence: 'high' | 'medium' | 'low';
  rootCause: string;
  severity: 'critical' | 'high' | 'medium' | 'low';
  issueTitle: string;
  issueBody: string;
  labels: string[];
}

// ─── Prompts ──────────────────────────────────────────────────────────────────

const SYSTEM_PROMPT = `You are an expert QA engineer and software debugger analyzing automated test failures.

Your task is to determine:
1. Whether this failure is an actual application bug vs. a test infrastructure/config/network issue.
2. The root cause of the failure.
3. The severity and relevant labels.

Classify as NOT a bug (isBug: false) when the failure is caused by:
- Timeouts or flaky network
- Missing environment variables or test config
- Test data setup problems
- Playwright selector instability
- CI/CD environment differences

Always respond with a single valid JSON object matching this exact schema — no prose, no markdown fences:
{
  "isBug": boolean,
  "confidence": "high" | "medium" | "low",
  "rootCause": "concise one-sentence explanation",
  "severity": "critical" | "high" | "medium" | "low",
  "issueTitle": "concise GitHub issue title, max 80 chars",
  "issueBody": "full GitHub issue body written in Markdown",
  "labels": ["array", "of", "relevant", "label", "strings"]
}

For issueBody use this Markdown template:
## Description
{rootCause expanded}

## Failing Test
- **Scenario:** {scenarioName}
- **Feature:** {featureFile}
- **Tags:** {tags}

## Error
\`\`\`
{errorMessage trimmed}
\`\`\`

## Expected Behavior
{what should have happened}

## Actual Behavior
{what actually happened}

## Severity & Impact
{impact assessment}

## Suggested Investigation
{concrete next steps for the dev team}

---
> 🤖 Auto-generated by AI failure analysis`;

// ─── Main export ──────────────────────────────────────────────────────────────

/**
 * Sends the test failure context to the GitHub Models API (GPT-4o-mini)
 * and returns a structured analysis result.
 *
 * Requires the GITHUB_TOKEN environment variable.
 * Returns null if the API is unavailable or the token is missing.
 */
export async function analyzeFailure(context: FailureContext): Promise<AnalysisResult | null> {
  const token = process.env.GITHUB_TOKEN;

  if (!token) {
    console.warn('[AI Analyzer] GITHUB_TOKEN not set — skipping AI analysis.');
    return null;
  }

  const client = new OpenAI({
    baseURL: 'https://models.inference.ai.azure.com',
    apiKey: token,
  });

  const model = process.env.AI_MODEL ?? 'gpt-4o-mini';

  const userPrompt = `Analyze this automated test failure and return the JSON analysis.

**Scenario:** ${context.scenarioName}
**Feature File:** ${context.featureFile}
**Tags:** ${context.tags.join(', ') || 'none'}

**Error Message:**
${context.errorMessage.substring(0, 1500)}

**Stack Trace:**
${context.stackTrace.substring(0, 2000)}`;

  try {
    const response = await client.chat.completions.create({
      model,
      messages: [
        { role: 'system', content: SYSTEM_PROMPT },
        { role: 'user', content: userPrompt },
      ],
      temperature: 0.1,
      response_format: { type: 'json_object' },
    });

    const raw = response.choices[0]?.message?.content;
    if (!raw) {
      console.warn('[AI Analyzer] Empty response from API.');
      return null;
    }

    return JSON.parse(raw) as AnalysisResult;
  } catch (err) {
    console.error('[AI Analyzer] Error calling GitHub Models API:', err);
    return null;
  }
}
